### ISSUE TITLE
Cannot be run after compiling using gradle

### ISSUE THREAD

**Issue by nico151999** [AnimbusDev/GEM-Player#51]
I love the design of the player, so it's a real pitty it seems to have stopped being developed. Anyway, I've just tried compiling it. However, after installing it on the phone I get FCs even though storage permissions were granted. I guess that's a common issue so maybe someone can help :D
Thanks a lot in advance!

**Comment by AdrianVovk** [comment]
Unfortunately, I haven't the time to keep it up to date, through an eventual rewrite is planned. To fix your current issue, just go into settings and give it the storage permission. It should work then

**Comment by nico151999** [comment]
Thanks for the quick answer, but you got me wrong. The storage permission is granted. It doesn't work though. FCs on launch. I'm not using your build which still works. I'm using my build of the latest commit in the indev branch which doesn't run at all. I wanted to check out what happened to the app after hundreds of commits since the latest release.

**Comment by AdrianVovk** [comment]
@nico151999 Oh ok. I haven't touched the project in years, so I don't remember if the latest commit hat issues. Could you send a stack trace?

**Comment by AdrianVovk** [comment]
How did you even get it to compile in the first place? App-theme-engine has since been discontinued and removed from repositories, and GEM depends on it.

**Comment by nico151999** [comment]
Sorry for not responding that quickly. I haven't had a deep look at the code so I didn't know how the build process works. I just thought it'd be enough to run envsetup.sh and gradlew build right after that. As I got a gradle error telling me there's an outdated plugin and I should export an environment variable, I just did so and it worked. What I also did was ignoring untranslated strings for the release build. But the build ran fine besides from that. The host runs Debian btw.

**Comment by AdrianVovk** [comment]
@nico151999 Odd. The other issue open here is about why it can't build. What error are you getting on running?

**Comment by nico151999** [comment]
I can't debug right now, I'm not at home. Will be back next Saturday presumably. I'll create an adb logcat as soon as possible.

**Comment by nico151999** [comment]
Hi, I'm back :D I couldn't get my hands to a Linux machine so I tried creating a log using windows. Should be satisfying though ;) Seems like the Theme engine you wrote about is the actual problem why the app cannot launch. I'd really appreciate further development of the project as this player's got an absolutely awesome philosophy aiming to match the Google IO player's design. Here's the log:

`C:\Program Files (x86)\Minimal ADB and Fastboot>adb logcat | findstr com.animbus.music
12-16 14:28:48.239  1105  1133 V BackupManagerService: restoreAtInstall pkg=com.animbus.music token=8 restoreSet=0
12-16 14:28:48.259  1105  1119 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.animbus.music flg=0x4000010 (has extras) } to com.android.musicfx/.Compatibility$Receiver
12-16 14:28:48.326  1105 20338 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.animbus.music flg=0x4000010 (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.googlequicksearchbox.GelStubAppWatcher
12-16 14:28:48.327  1105  1119 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.animbus.music flg=0x4000010 (has extras) } to com.google.android.ims/.receivers.RcsAutoStartReceiver
12-16 14:28:59.280  1105 20338 I ActivityManager: START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:com.animbus.music flg=0x10008000 cmp=com.android.settings/.applications.InstalledAppDetails} from uid 1000
12-16 14:29:45.317  1105  1529 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.animbus.music/.activities.app.icon.srini.black bnds=[1132,955][1408,1400] (has extras)} from uid 10143
12-16 14:29:45.341  1105  1529 I ActivityManager: Start proc 13638:com.animbus.music/u0a203 for activity com.animbus.music/.activities.app.icon.srini.black
12-16 14:29:45.463  1105  2495 I ActivityManager: Process com.animbus.music (pid 13638) has died: fore TOP
12-16 14:29:45.464  1105  2495 W ActivityManager: Scheduling restart of crashed service com.animbus.music/.media.stable.MediaService in 1000ms
12-16 14:29:45.475  1105  2495 I ActivityManager: Start proc 13657:com.animbus.music/u0a203 for activity com.animbus.music/.activities.app.icon.srini.black
12-16 14:29:45.482  1105  1347 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x4000004 cmp=com.animbus.music/.ui.activity.mainScreen.MainScreen (has extras)} from uid 10203
12-16 14:29:45.483  1105  1347 W ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { act=android.intent.action.MAIN flg=0x4000004 cmp=com.animbus.music/.ui.activity.mainScreen.MainScreen (has extras) }
12-16 14:29:45.685 13657 13657 E AndroidRuntime: Process: com.animbus.music, PID: 13657
12-16 14:29:45.685 13657 13657 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.animbus.music/com.animbus.music.ui.activity.mainScreen.MainScreen}: java.lang.IllegalStateException: Cannot execute task: the task is already running.
12-16 14:29:45.685 13657 13657 E AndroidRuntime:        at com.animbus.music.tasks.Loader.run(Loader.java:152)
12-16 14:29:45.685 13657 13657 E AndroidRuntime:        at com.animbus.music.media.Library.build(Library.java:129)
12-16 14:29:45.685 13657 13657 E AndroidRuntime:        at com.animbus.music.ui.activity.mainScreen.MainScreen.requestPermissions(MainScreen.java:129)
12-16 14:29:45.685 13657 13657 E AndroidRuntime:        at com.animbus.music.ui.activity.mainScreen.MainScreen.setUp(MainScreen.java:115)
12-16 14:29:45.685 13657 13657 E AndroidRuntime:        at com.animbus.music.ui.custom.activity.ThemeActivity.sequence(ThemeActivity.java:96)
12-16 14:29:45.685 13657 13657 E AndroidRuntime:        at com.animbus.music.ui.custom.activity.ThemeActivity.onCreate(ThemeActivity.java:63)
12-16 14:29:45.688  1105 20498 W ActivityManager:   Force finishing activity com.animbus.music/.ui.activity.mainScreen.MainScreen
12-16 14:29:45.698  1105  1120 I ActivityManager: Showing crash dialog for package com.animbus.music u0
12-16 14:29:46.191  1105  1119 W ActivityManager: Activity pause timeout for ActivityRecord{e668321 u0 com.animbus.music/.ui.activity.mainScreen.MainScreen t3405 f}
12-16 14:29:55.814  1105 20498 I ActivityManager: Killing 13657:com.animbus.music/u0a203 (adj 902): crash
12-16 14:29:55.815  1105 20498 W ActivityManager: Scheduling restart of crashed service com.animbus.music/.media.stable.MediaService in 4000ms
12-16 14:29:55.848  1105 20498 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.animbus.music/.ui.activity.mainScreen.MainScreen (has extras)} from uid 10143
12-16 14:29:55.864  1105  2473 I ActivityManager: Start proc 13696:com.animbus.music/u0a203 for activity com.animbus.music/.ui.activity.mainScreen.MainScreen
12-16 14:29:56.097 13696 13696 E AndroidRuntime: Process: com.animbus.music, PID: 13696
12-16 14:29:56.097 13696 13696 E AndroidRuntime: java.lang.ClassCastException: com.animbus.music.media.objects.Album cannot be cast to com.animbus.music.media.objects.Song
12-16 14:29:56.097 13696 13696 E AndroidRuntime:        at com.animbus.music.ui.ItemSongList.setVariable(ItemSongList.java:64)
12-16 14:29:56.097 13696 13696 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter$BasicViewHolder.update(ListAdapter.java:191)
12-16 14:29:56.097 13696 13696 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter.onBindViewHolder(ListAdapter.java:160)
12-16 14:29:56.097 13696 13696 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter.onBindViewHolder(ListAdapter.java:79)
12-16 14:29:56.099  1105 20498 W ActivityManager:   Force finishing activity com.animbus.music/.ui.activity.mainScreen.MainScreen
12-16 14:29:56.102  1105  1120 I ActivityManager: Showing crash dialog for package com.animbus.music u0
12-16 14:29:56.600  1105  1119 W ActivityManager: Activity pause timeout for ActivityRecord{86eaea1 u0 com.animbus.music/.ui.activity.mainScreen.MainScreen t3406 f}
12-16 14:29:56.675  1105  1119 I WindowManager: Failed to capture screenshot of Token{1db98c6 ActivityRecord{86eaea1 u0 com.animbus.music/.ui.activity.mainScreen.MainScreen t3406 f}} appWin=Window{ed76249 u0 com.animbus.music/com.animbus.music.ui.activity.mainScreen.MainScreen} drawState=1
12-16 14:30:00.688  1105 20498 W ActivityManager:   Force finishing activity com.animbus.music/.ui.activity.mainScreen.MainScreen
12-16 14:30:00.725  1105 20498 I ActivityManager: Killing 13696:com.animbus.music/u0a203 (adj 900): crash
12-16 14:35:18.252  1105 20494 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.animbus.music/.activities.app.icon.srini.black bnds=[1132,1854][1408,2299] (has extras)} from uid 10143
12-16 14:35:18.269  1105 20494 I ActivityManager: Start proc 14045:com.animbus.music/u0a203 for activity com.animbus.music/.activities.app.icon.srini.black
12-16 14:35:18.311 14045 14045 I chatty  : uid=10203(com.animbus.music) expire 88 lines
12-16 14:35:18.313 14045 14061 I chatty  : uid=10203(com.animbus.music) expire 3 lines
12-16 14:35:18.395 14045 14067 I chatty  : uid=10203(com.animbus.music) expire 6 lines
12-16 14:35:18.403 14045 14065 I chatty  : uid=10203(com.animbus.music) expire 2 lines
12-16 14:35:18.420 14045 14063 I chatty  : uid=10203(com.animbus.music) expire 66 lines
12-16 14:35:18.421 14045 14064 I chatty  : uid=10203(com.animbus.music) expire 239 lines
12-16 14:35:18.428 14045 14063 I chatty  : uid=10203(com.animbus.music) expire 92 lines
12-16 14:35:18.429 14045 14045 I chatty  : uid=10203(com.animbus.music) expire 23 lines
12-16 14:35:18.439 14045 14064 I chatty  : uid=10203(com.animbus.music) expire 149 lines
12-16 14:35:18.439 14045 14063 I chatty  : uid=10203(com.animbus.music) expire 94 lines
12-16 14:35:18.449 14045 14050 I chatty  : uid=10203(com.animbus.music) expire 3 lines
12-16 14:35:18.450 14045 14064 I chatty  : uid=10203(com.animbus.music) expire 101 lines
12-16 14:35:18.450 14045 14045 I chatty  : uid=10203(com.animbus.music) expire 10 lines
12-16 14:35:18.450 14045 14063 I chatty  : uid=10203(com.animbus.music) expire 1432 lines
12-16 14:35:18.453 14045 14045 E AndroidRuntime: Process: com.animbus.music, PID: 14045
12-16 14:35:18.453 14045 14045 E AndroidRuntime: java.lang.ClassCastException: com.animbus.music.media.objects.Playlist cannot be cast to com.animbus.music.media.objects.Album
12-16 14:35:18.453 14045 14045 E AndroidRuntime:        at com.animbus.music.ui.ItemAlbum.setVariable(ItemAlbum.java:73)
12-16 14:35:18.453 14045 14045 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter$BasicViewHolder.update(ListAdapter.java:191)
12-16 14:35:18.453 14045 14045 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter.onBindViewHolder(ListAdapter.java:160)
12-16 14:35:18.453 14045 14045 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter.onBindViewHolder(ListAdapter.java:79)
12-16 14:35:18.455  1105 20493 W ActivityManager:   Force finishing activity com.animbus.music/.activities.app.icon.srini.black
12-16 14:35:18.457  1105  1120 I ActivityManager: Showing crash dialog for package com.animbus.music u0
12-16 14:35:18.956  1105  1119 W ActivityManager: Activity pause timeout for ActivityRecord{59f9437 u0 com.animbus.music/.activities.app.icon.srini.black t3407 f}
12-16 14:35:18.985  1105  1119 I WindowManager: Failed to capture screenshot of Token{da50da4 ActivityRecord{59f9437 u0 com.animbus.music/.activities.app.icon.srini.black t3407 f}} appWin=Window{1d0b479 u0 com.animbus.music/com.animbus.music.activities.app.icon.srini.black} drawState=1
12-16 14:35:22.462  1105 20493 W ActivityManager:   Force finishing activity com.animbus.music/.activities.app.icon.srini.black
12-16 14:35:22.504  1105 20493 I ActivityManager: Killing 14045:com.animbus.music/u0a203 (adj 900): crash
12-16 14:35:23.382  1105 20493 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.animbus.music/.activities.app.icon.srini.black bnds=[1132,1854][1408,2299] (has extras)} from uid 10143
12-16 14:35:23.401  1105  2433 I ActivityManager: Start proc 14073:com.animbus.music/u0a203 for activity com.animbus.music/.activities.app.icon.srini.black
12-16 14:35:23.481 14073 14073 D InflationInterceptor: com.animbus.music.ui.custom.view.LockableViewPager inflated to -> com.animbus.music.ui.custom.view.LockableViewPager
12-16 14:35:23.483 14073 14073 D InflationInterceptor: com.animbus.music.ui.custom.view.SquareImageViewHeight_Based inflated to -> com.animbus.music.ui.custom.view.SquareImageViewHeight_Based
12-16 14:35:23.492 14073 14073 W Resources:     at com.animbus.music.ui.custom.activity.ThemeActivity.sequence(ThemeActivity.java:86)
12-16 14:35:23.492 14073 14073 W Resources:     at com.animbus.music.ui.custom.activity.ThemeActivity.onCreate(ThemeActivity.java:63)
12-16 14:35:23.493 14073 14073 W Resources:     at com.animbus.music.ui.custom.activity.ThemeActivity.sequence(ThemeActivity.java:86)
12-16 14:35:23.493 14073 14073 W Resources:     at com.animbus.music.ui.custom.activity.ThemeActivity.onCreate(ThemeActivity.java:63)
12-16 14:35:23.504 14073 14073 W System.err:    at com.animbus.music.ui.activity.mainScreen.MainScreen.switchTab(MainScreen.java:404)
12-16 14:35:23.504 14073 14073 W System.err:    at com.animbus.music.ui.activity.mainScreen.MainScreen.switchToArtists(MainScreen.java:442)
12-16 14:35:23.504 14073 14073 W System.err:    at com.animbus.music.ui.activity.mainScreen.MainScreen.setUp(MainScreen.java:112)
12-16 14:35:23.504 14073 14073 W System.err:    at com.animbus.music.ui.custom.activity.ThemeActivity.sequence(ThemeActivity.java:96)
12-16 14:35:23.504 14073 14073 W System.err:    at com.animbus.music.ui.custom.activity.ThemeActivity.onCreate(ThemeActivity.java:63)
12-16 14:35:23.592 14073 14073 D InflationInterceptor: com.animbus.music.ui.custom.view.SquareImageViewWidth_Based inflated to -> com.animbus.music.ui.custom.view.SquareImageViewWidth_Based
12-16 14:35:23.606 14073 14073 D InflationInterceptor: com.animbus.music.ui.custom.view.SquareImageViewWidth_Based inflated to -> com.animbus.music.ui.custom.view.SquareImageViewWidth_Based
12-16 14:35:23.610 14073 14073 D InflationInterceptor: com.animbus.music.ui.custom.view.SquareImageViewWidth_Based inflated to -> com.animbus.music.ui.custom.view.SquareImageViewWidth_Based
12-16 14:35:23.614 14073 14073 D InflationInterceptor: com.animbus.music.ui.custom.view.SquareImageViewWidth_Based inflated to -> com.animbus.music.ui.custom.view.SquareImageViewWidth_Based
12-16 14:35:23.618 14073 14073 D InflationInterceptor: com.animbus.music.ui.custom.view.SquareImageViewWidth_Based inflated to -> com.animbus.music.ui.custom.view.SquareImageViewWidth_Based
12-16 14:35:23.621 14073 14073 D InflationInterceptor: com.animbus.music.ui.custom.view.SquareImageViewWidth_Based inflated to -> com.animbus.music.ui.custom.view.SquareImageViewWidth_Based
12-16 14:35:23.627 14073 14073 D InflationInterceptor: Parent of com.animbus.music.ui.custom.view.SquareImageViewHeight_Based had the ate_ignore tag set, inflating default.
12-16 14:35:23.627 14073 14073 D InflationInterceptor: com.animbus.music.ui.custom.view.SquareImageViewHeight_Based inflated to -> com.animbus.music.ui.custom.view.SquareImageViewHeight_Based
12-16 14:35:23.630 14073 14073 E AndroidRuntime: Process: com.animbus.music, PID: 14073
12-16 14:35:23.630 14073 14073 E AndroidRuntime: java.lang.ClassCastException: com.animbus.music.media.objects.Album cannot be cast to com.animbus.music.media.objects.Song
12-16 14:35:23.630 14073 14073 E AndroidRuntime:        at com.animbus.music.ui.ItemSongList.setVariable(ItemSongList.java:64)
12-16 14:35:23.630 14073 14073 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter$BasicViewHolder.update(ListAdapter.java:191)
12-16 14:35:23.630 14073 14073 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter.onBindViewHolder(ListAdapter.java:160)
12-16 14:35:23.630 14073 14073 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter.onBindViewHolder(ListAdapter.java:79)
12-16 14:35:23.632  1105 20494 W ActivityManager:   Force finishing activity com.animbus.music/.activities.app.icon.srini.black
12-16 14:35:23.634  1105  1120 I ActivityManager: Showing crash dialog for package com.animbus.music u0
12-16 14:35:24.133  1105  1119 W ActivityManager: Activity pause timeout for ActivityRecord{45eaf3d u0 com.animbus.music/.activities.app.icon.srini.black t3408 f}
12-16 14:35:24.164  1105  1119 I WindowManager: Failed to capture screenshot of Token{be36332 ActivityRecord{45eaf3d u0 com.animbus.music/.activities.app.icon.srini.black t3408 f}} appWin=Window{76c052e u0 com.animbus.music/com.animbus.music.activities.app.icon.srini.black} drawState=1
12-16 14:35:24.580  1105 20494 W ActivityManager:   Force finishing activity com.animbus.music/.activities.app.icon.srini.black
12-16 14:35:24.581  1105 20494 I ActivityManager: Killing 14073:com.animbus.music/u0a203 (adj 900): crash
12-16 14:35:24.594  1105  1403 W InputDispatcher: channel '76c052e com.animbus.music/com.animbus.music.activities.app.icon.srini.black (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-16 14:35:24.594  1105  1403 E InputDispatcher: channel '76c052e com.animbus.music/com.animbus.music.activities.app.icon.srini.black (server)' ~ Channel is unrecoverably broken and will be disposed!
12-16 14:35:24.595  1105  2433 I WindowManager: WIN DEATH: Window{76c052e u0 com.animbus.music/com.animbus.music.activities.app.icon.srini.black}
12-16 14:35:24.595  1105  2433 W InputDispatcher: Attempted to unregister already unregistered input channel '76c052e com.animbus.music/com.animbus.music.activities.app.icon.srini.black (server)'
12-16 14:35:26.191  1105 20499 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.animbus.music/.activities.app.icon.srini.black bnds=[1132,1854][1408,2299] (has extras)} from uid 10143
12-16 14:35:26.210  1105  1665 I ActivityManager: Start proc 14107:com.animbus.music/u0a203 for activity com.animbus.music/.activities.app.icon.srini.black
12-16 14:35:26.276 14107 14107 D InflationInterceptor: com.animbus.music.ui.custom.view.LockableViewPager inflated to -> com.animbus.music.ui.custom.view.LockableViewPager
12-16 14:35:26.278 14107 14107 D InflationInterceptor: com.animbus.music.ui.custom.view.SquareImageViewHeight_Based inflated to -> com.animbus.music.ui.custom.view.SquareImageViewHeight_Based
12-16 14:35:26.287 14107 14107 W Resources:     at com.animbus.music.ui.custom.activity.ThemeActivity.sequence(ThemeActivity.java:86)
12-16 14:35:26.287 14107 14107 W Resources:     at com.animbus.music.ui.custom.activity.ThemeActivity.onCreate(ThemeActivity.java:63)
12-16 14:35:26.287 14107 14107 W Resources:     at com.animbus.music.ui.custom.activity.ThemeActivity.sequence(ThemeActivity.java:86)
12-16 14:35:26.287 14107 14107 W Resources:     at com.animbus.music.ui.custom.activity.ThemeActivity.onCreate(ThemeActivity.java:63)
12-16 14:35:26.298 14107 14107 W System.err:    at com.animbus.music.ui.activity.mainScreen.MainScreen.switchTab(MainScreen.java:404)
12-16 14:35:26.298 14107 14107 W System.err:    at com.animbus.music.ui.activity.mainScreen.MainScreen.switchToArtists(MainScreen.java:442)
12-16 14:35:26.298 14107 14107 W System.err:    at com.animbus.music.ui.activity.mainScreen.MainScreen.setUp(MainScreen.java:112)
12-16 14:35:26.298 14107 14107 W System.err:    at com.animbus.music.ui.custom.activity.ThemeActivity.sequence(ThemeActivity.java:96)
12-16 14:35:26.298 14107 14107 W System.err:    at com.animbus.music.ui.custom.activity.ThemeActivity.onCreate(ThemeActivity.java:63)
12-16 14:35:26.411 14107 14107 D InflationInterceptor: com.animbus.music.ui.custom.view.SquareImageViewWidth_Based inflated to -> com.animbus.music.ui.custom.view.SquareImageViewWidth_Based
12-16 14:35:26.424 14107 14107 D InflationInterceptor: com.animbus.music.ui.custom.view.SquareImageViewWidth_Based inflated to -> com.animbus.music.ui.custom.view.SquareImageViewWidth_Based
12-16 14:35:26.427 14107 14107 E AndroidRuntime: Process: com.animbus.music, PID: 14107
12-16 14:35:26.427 14107 14107 E AndroidRuntime: java.lang.ClassCastException: com.animbus.music.media.objects.Song cannot be cast to com.animbus.music.media.objects.Album
12-16 14:35:26.427 14107 14107 E AndroidRuntime:        at com.animbus.music.ui.ItemAlbum.setVariable(ItemAlbum.java:73)
12-16 14:35:26.427 14107 14107 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter$BasicViewHolder.update(ListAdapter.java:191)
12-16 14:35:26.427 14107 14107 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter.onBindViewHolder(ListAdapter.java:160)
12-16 14:35:26.427 14107 14107 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter.onBindViewHolder(ListAdapter.java:79)
12-16 14:35:26.429  1105 20499 W ActivityManager:   Force finishing activity com.animbus.music/.activities.app.icon.srini.black
12-16 14:35:26.431  1105  1120 I ActivityManager: Showing crash dialog for package com.animbus.music u0
12-16 14:35:26.930  1105  1119 W ActivityManager: Activity pause timeout for ActivityRecord{9b36d9f u0 com.animbus.music/.activities.app.icon.srini.black t3409 f}
12-16 14:35:26.954  1105  1119 I WindowManager: Failed to capture screenshot of Token{4c64eec ActivityRecord{9b36d9f u0 com.animbus.music/.activities.app.icon.srini.black t3409 f}} appWin=Window{2d5fd08 u0 com.animbus.music/com.animbus.music.activities.app.icon.srini.black} drawState=1
12-16 14:35:33.768  1105 20499 W ActivityManager:   Force finishing activity com.animbus.music/.activities.app.icon.srini.black
12-16 14:35:33.808  1105 20499 I ActivityManager: Killing 14107:com.animbus.music/u0a203 (adj 902): crash
12-16 14:37:06.982  1105  2473 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.animbus.music/.activities.app.icon.srini.black bnds=[1132,2001][1408,2446] (has extras)} from uid 10143
12-16 14:37:07.006  1105  2473 I ActivityManager: Start proc 14330:com.animbus.music/u0a203 for activity com.animbus.music/.activities.app.icon.srini.black
12-16 14:37:07.081 14330 14330 D InflationInterceptor: com.animbus.music.ui.custom.view.LockableViewPager inflated to -> com.animbus.music.ui.custom.view.LockableViewPager
12-16 14:37:07.082 14330 14330 D InflationInterceptor: com.animbus.music.ui.custom.view.SquareImageViewHeight_Based inflated to -> com.animbus.music.ui.custom.view.SquareImageViewHeight_Based
12-16 14:37:07.093 14330 14330 W Resources:     at com.animbus.music.ui.custom.activity.ThemeActivity.sequence(ThemeActivity.java:86)
12-16 14:37:07.093 14330 14330 W Resources:     at com.animbus.music.ui.custom.activity.ThemeActivity.onCreate(ThemeActivity.java:63)
12-16 14:37:07.093 14330 14330 W Resources:     at com.animbus.music.ui.custom.activity.ThemeActivity.sequence(ThemeActivity.java:86)
12-16 14:37:07.093 14330 14330 W Resources:     at com.animbus.music.ui.custom.activity.ThemeActivity.onCreate(ThemeActivity.java:63)
12-16 14:37:07.105 14330 14330 W System.err:    at com.animbus.music.ui.activity.mainScreen.MainScreen.switchTab(MainScreen.java:404)
12-16 14:37:07.105 14330 14330 W System.err:    at com.animbus.music.ui.activity.mainScreen.MainScreen.switchToArtists(MainScreen.java:442)
12-16 14:37:07.105 14330 14330 W System.err:    at com.animbus.music.ui.activity.mainScreen.MainScreen.setUp(MainScreen.java:112)
12-16 14:37:07.105 14330 14330 W System.err:    at com.animbus.music.ui.custom.activity.ThemeActivity.sequence(ThemeActivity.java:96)
12-16 14:37:07.105 14330 14330 W System.err:    at com.animbus.music.ui.custom.activity.ThemeActivity.onCreate(ThemeActivity.java:63)
12-16 14:37:07.180 14330 14330 D InflationInterceptor: com.animbus.music.ui.custom.view.SquareImageViewWidth_Based inflated to -> com.animbus.music.ui.custom.view.SquareImageViewWidth_Based
12-16 14:37:07.189 14330 14330 E AndroidRuntime: Process: com.animbus.music, PID: 14330
12-16 14:37:07.189 14330 14330 E AndroidRuntime: java.lang.ClassCastException: com.animbus.music.media.objects.Playlist cannot be cast to com.animbus.music.media.objects.Album
12-16 14:37:07.189 14330 14330 E AndroidRuntime:        at com.animbus.music.ui.ItemAlbum.setVariable(ItemAlbum.java:73)
12-16 14:37:07.189 14330 14330 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter$BasicViewHolder.update(ListAdapter.java:191)
12-16 14:37:07.189 14330 14330 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter.onBindViewHolder(ListAdapter.java:160)
12-16 14:37:07.189 14330 14330 E AndroidRuntime:        at com.animbus.music.ui.list.ListAdapter.onBindViewHolder(ListAdapter.java:79)
12-16 14:37:07.192  1105  1742 W ActivityManager:   Force finishing activity com.animbus.music/.activities.app.icon.srini.black
12-16 14:37:07.197  1105  1120 I ActivityManager: Showing crash dialog for package com.animbus.music u0
12-16 14:37:07.693  1105  1119 W ActivityManager: Activity pause timeout for ActivityRecord{d7d00d8 u0 com.animbus.music/.activities.app.icon.srini.black t3411 f}
12-16 14:37:07.715  1105  1119 I WindowManager: Failed to capture screenshot of Token{38b5c31 ActivityRecord{d7d00d8 u0 com.animbus.music/.activities.app.icon.srini.black t3411 f}} appWin=Window{1adac52 u0 com.animbus.music/com.animbus.music.activities.app.icon.srini.black} drawState=1
12-16 14:37:12.648  1105  1742 W ActivityManager:   Force finishing activity com.animbus.music/.activities.app.icon.srini.black
12-16 14:37:12.680  1105  1742 I ActivityManager: Killing 14330:com.animbus.music/u0a203 (adj 902): crash`

**Comment by AdrianVovk** [comment]
@nico151999 Actually it looks like it is crashing due to loading. It tries to load in your music twice, causing the first crash. There seems to be another crash, where it tries to convert an album into a playlist

In short, it's really broken. I might revive the project, as I really do miss that design

**Comment by nico151999** [comment]
I've just installed your version from the PlayStore. In case you're willing to continue the Project I'd have a recommendation: every time you click an album art to open an album specific activity there's a shared elements transition. However, there are some graphical glitches. I've faced such issues already and I could solve them by removing the padding from the view element. In your case this would be the transitioning text. Adjusting text appearance settings may also cause such glitches...

**Comment by AdrianVovk** [comment]
@nico151999 Alright, that's good to know. Thanks!
